// GENERATED from tools/translations/*_tokens.tsv -- do not edit by hand.
// Regenerate: python3 tools/gen_menugen_tokens.py
// German job-name token -> English, merged over the base table in menugen.js.
const MENUGEN_TSV_TOKENS = {
"40BYTES": "40 Bytes",
"ABBAUEN": "Reduce",
"ABBLENDEN": "Dim",
"ABBRUCH": "Abort",
"ABFRAGE": "Query",
"ABFRAGEN": "Query",
"ABGASKLAPPE": "Exhaust Flap",
"ABGASTEMP": "Exhaust Temp",
"ABGASTEMPERATUR": "Exhaust Temperature",
"ABGLEICH": "Adjustment",
"ABGLEICHEN": "Calibrate",
"ABGLEICHFLAG": "Calibration Flag",
"ABGLEICHWERT": "Adjustment Value",
"ABGLEICHWERTE": "Calibration Values",
"ABNUETZUNGSINDEX": "Wear Index",
"ABRISS": "Cutoff",
"ABS": "ABS",
"ABSCHALTBEDINGUNG": "Shutoff Condition",
"ABSCHALTUNG": "Shutdown",
"ABSOLUT": "Absolute",
"ABSOLUTER": "Absolute",
"ABSTAND": "Distance",
"ABSTIME": "Absolute Time",
"ABTRIEBSDREHZ": "Output Speed",
"ABTRIEBSDREHZAHL": "Output Speed",
"AC": "AC",
"ACC": "Active Cruise Control",
"ACCELERATION": "Acceleration",
"ACCELLERATION": "Acceleration",
"ACCESS": "Access",
"ACHSE": "Axle",
"ACT": "Actual",
"ACTIVATION": "Activation",
"ACTUATOR": "Actuator",
"ACTUATORS": "Actuators",
"AD": "Analog-Digital",
"ADAP": "Adaptation",
"ADAP2": "Adaptation 2",
"ADAPT": "Adaptation",
"ADAPTION": "Adaptation",
"ADAPTIONSSPEICHER": "Adaptation Memory",
"ADAPTIONSWERT": "Adaptation Value",
"ADAPTIONSWERTE": "Adaptation Values",
"ADAPTIVDATEN": "Adaptive Data",
"ADAPTIVE": "Adaptive",
"ADAPTIVWERT": "Adaptive Value",
"ADAS": "ADAS",
"ADC": "ADC",
"ADD": "Add",
"ADDRCODINGDEFAULT": "Address Coding Default",
"ADDRESS": "Address",
"ADR": "Address",
"ADRECOVERY": "Address Recovery",
"ADRESSBUCH": "Address Book",
"ADRESSEN": "Addresses",
"AEI": "AEI",
"AENDERN": "Change",
"AENDERUNG": "Change",
"AENDERUNGSINDEX": "Change Index",
"AFS": "Adaptive Headlights",
"AGGREGATE": "Aggregates",
"AGK": "Exhaust Flap",
"AGR": "EGR",
"AGS": "Automatic Transmission Control",
"AHL": "Adaptive Headlight",
"AIC": "AIC",
"AIF": "AIF",
"AIM": "AIM",
"AIRBAGS": "Airbags",
"AIRCON": "Air Conditioning",
"AKT": "Current",
"AKTION": "Action",
"AKTIV": "Active",
"AKTIVE": "Active",
"AKTIVES": "Active",
"AKTIVIEREN": "Activate",
"AKTIVIERUNG": "Activation",
"AKTOREN": "Actuators",
"AKTORIK": "Actuators",
"AKTUALISIEREN": "Update",
"AKTUATOR": "Actuator",
"AKTUATORIK": "Actuators",
"AKTUELL": "Current",
"AKTUELLE": "Current",
"AKTUELLES": "Current",
"ALARM": "Alarm",
"ALARMCOUNTER": "Alarm Counter",
"ALARMTEST": "Alarm Test",
"ALARMTRIGGER": "Alarm Trigger",
"ALC": "ALC",
"ALIVE": "Alive",
"ALL": "All",
"ALLE": "All",
"ALLES": "All",
"ALLGEMEIN": "General",
"ALT": "Old",
"AMPERE": "Ampere",
"AMPLIFIER": "Amplifier",
"AMPLITUDEN": "Amplitudes",
"AN": "On",
"ANA": "Analog",
"ANALOG": "Analog",
"ANALOGE": "Analog",
"ANALOGEINGAENGE": "Analog Inputs",
"ANALOGSIGNALE": "Analog Signals",
"ANALOGUE": "Analogue",
"ANALOGWERTE": "Analog Values",
"ANALYSE": "Analysis",
"ANALYSIS": "Analysis",
"AND": "And",
"ANFAHREN": "Start",
"ANGEZEIGTER": "Displayed",
"ANHEBUNG": "Increase",
"ANLASSERFREIGABE": "Starter Enable",
"ANLEGEMODUS": "Apply Mode",
"ANLERNEN": "Teach-In",
"ANLIEFERPOSITION": "Delivery Position",
"ANSAUGLUFTTEMPERATUR": "Intake Air Temp",
"ANSCHLAG": "Stop",
"ANSTEUERSIGNAL": "Control Signal",
"ANSTEUERUNG": "Activation",
"ANSTOSSEN": "Trigger",
"ANT": "Drive",
"ANTENNA": "Antenna",
"ANTENNE": "Antenna",
"ANTENNE1": "Antenna 1",
"ANTENNE2": "Antenna 2",
"ANTENNEN": "Antennas",
"ANTENNENKONFIGURATION": "Antenna Configuration",
"ANTENNENSPANNUNG": "Antenna Voltage",
"ANTENNENSTROM": "Antenna Current",
"ANTRIEBE": "Drives",
"ANTWORTET": "Responds",
"ANZ": "Count",
"ANZEIGE": "Indicator",
"ANZEIGEN": "Displays",
"ANZUGSKRAFT": "Clamping Force",
"ANZUGSPOS": "Tightening Position",
"APP": "App",
"APPL": "Application",
"APPLICATION": "Application",
"APPLIKATION": "Application",
"ARG": "EGR",
"ARGUMENT": "Argument",
"ARRAY": "Array",
"ARS": "Active Roll Stabilization",
"ASC": "Stability Control",
"ASCET": "ASCET",
"ASCII": "ASCII",
"ASK": "Audio System Controller",
"ASSEMBLY": "Assembly",
"ASW": "Application Software",
"ATC": "Transfer Case",
"ATEMP": "Ambient Temp",
"ATF": "Transmission Fluid",
"ATMEL": "Atmel",
"ATMOS": "Atmosphere",
"ATMOSPHAERENDRUCK": "Atmospheric Pressure",
"AUC": "Air Quality Sensor",
"AUDIO": "Audio",
"AUDIOKANAELE": "Audio Channels",
"AUDIOMATRIX": "Audio Matrix",
"AUF": "Open",
"AUFRECHT": "Maintain",
"AUFRUFE": "Calls",
"AUFTRAG": "Request",
"AUFTRAG2": "Order 2",
"AUS": "Off",
"AUSBLENDEN": "Suppress",
"AUSGABE": "Output",
"AUSGAENGE": "Outputs",
"AUSGANG": "Output",
"AUSGEBEN": "Output",
"AUSL": "Exhaust",
"AUSLASS": "Exhaust",
"AUSLASTUNG": "Load",
"AUSLESEN": "Read Out",
"AUSLIEFERZUSTAND": "Delivery State",
"AUSLOESEN": "Trigger",
"AUSLOESUNGEN": "Triggers",
"AUSRICHTUNG": "Alignment",
"AUSRICHTUNGSTEST": "Alignment Test",
"AUSSCHALTEN": "Switch Off",
"AUSSCHWINGZEITEN": "Settling Times",
"AUSSEN": "Exterior",
"AUSSENSPIEGEL": "Exterior Mirror",
"AUSSENTEMP": "Outside Temp",
"AUSSETZER": "Misfire",
"AUSSTATTUNG": "Equipment",
"AUTHENT": "Authentication",
"AUTO": "Auto",
"AUTOADRESIERUNG": "Auto Addressing",
"AUTOADRESSIERUNG": "Auto Addressing",
"AUTODETEKT": "Auto Detect",
"AUTOINIT": "Auto Init",
"AUTORUN": "Autorun",
"AUTOSTORE": "Auto Store",
"AUX": "Aux",
"AUXVERBINDUNG": "Aux Connection",
"AVAILABLE": "Available",
"AVERAGE": "Average",
"AXIS": "Axis",
"BACKLIGHT": "Backlight",
"BAND": "Assembly Line",
"BANK1": "Bank 1",
"BANK2": "Bank 2",
"BARCODE": "Barcode",
"BASE": "Base",
"BASESTATION": "Base Station",
"BASIC": "Basic",
"BASISINITIALISIERUNG": "Base Initialization",
"BASS": "Bass",
"BATT": "Battery",
"BATTERIE": "Battery",
"BATTERIEINTEGRATOR": "Battery Integrator",
"BATTERIEKALIBRIERUNGSWERTE": "Battery Calibration Values",
"BATTERIELADUNGSZUSTAND": "Battery Charge State",
"BATTERIELEITUNGSDIAGNOSE": "Battery Cable Diagnosis",
"BATTERIESPANNUNG": "Battery Voltage",
"BATTERIETAUSCH": "Battery Replacement",
"BATTERIETRENNGRUND": "Battery Disconnect Reason",
"BATTERIETRENNUNGSANZAHL": "Battery Disconnect Count",
"BATTERIEZUSTAND": "Battery State",
"BATTERY": "Battery",
"BAUDRATEN": "Baud Rates",
"BAUREIHE": "Series",
"BC": "Onboard Computer",
"BEACON": "Beacon",
"BEDARF": "Demand",
"BEDIENANFORDERUNGEN": "Operating Requests",
"BEDIENELEMENT": "Control Element",
"BEDIENGERAET": "Control Unit",
"BEDIENKONZEPT": "Operating Concept",
"BEDIENKONZEPTZUSTAENDE": "Operating Concept States",
"BEDIENSCHALTER": "Control Switch",
"BEDIENSTATISTIK": "Operating Statistics",
"BEDIENTASTER": "Control Button",
"BEDIENTEIL": "Control Unit",
"BEDIENUNG": "Operation",
"BEENDEN": "End",
"BEFUELL": "Fill",
"BEGRENZ": "Limit",
"BELADUNGSSENSOR": "Load Sensor",
"BELASTUNG": "Load",
"BELEUCHTUNG": "Lighting",
"BELU": "Ventilation",
"BELUEFTUNG": "Ventilation",
"BER": "Range",
"BEREICH": "Range",
"BEREICHE": "Ranges",
"BESCHLAG": "Fogging",
"BESCHLAGSENSOR": "Fogging Sensor",
"BESCHLEUNIGUNG": "Acceleration",
"BEST": "Best",
"BESTROMEN": "Energize",
"BESTROMUNGSZEIT": "Energization Time",
"BETAETIGUNGEN": "Actuations",
"BETAETIGUNGSZAEHLER": "Actuation Counter",
"BETR": "Operation",
"BETRIEBSART": "Operating Mode",
"BETRIEBSDATEN": "Operating Data",
"BETRIEBSMODE": "Operating Mode",
"BETRIEBSSPANNUNG": "Operating Voltage",
"BETRIEBSSTUNDEN": "Operating Hours",
"BETRIEBSSTUNDENZAEHLER": "Operating Hours Counter",
"BILD": "Image",
"BILDEN": "Form",
"BIN": "Binary",
"BIS": "Up To",
"BIT": "Bit",
"BLAU": "Blue",
"BLINKER": "Turn Signal",
"BLINKERRUECKSTELLUNG": "Turn Signal Reset",
"BLOCK": "Block",
"BLOCK1": "Block 1",
"BLOCK2": "Block 2",
"BLOCK3": "Block 3",
"BLOCK4": "Block 4",
"BLOCKIERUNG": "Blocking",
"BLOCKLAENGE": "Block Length",
"BLOECKEANZAHL": "Block Count",
"BLS": "Brake Light Switch",
"BMW": "BMW",
"BODY": "Body",
"BOOST": "Boost",
"BOOT": "Boot",
"BOOTLOADER": "Bootloader",
"BOOTLOADERSWVERSION": "Bootloader SW Version",
"BOOTVERSION": "Boot Version",
"BORDNETZSPANNUNG": "Vehicle Voltage",
"BORDSPANNUNG": "System Voltage",
"BOSCH": "Bosch",
"BOTSCHAFTEN": "Messages",
"BREMSEN": "Brakes",
"BREMSENTEMPERATUR": "Brake Temperature",
"BREMSLICHTSCHALTER": "Brake Light Switch",
"BROSE": "Brose",
"BROWSER": "Browser",
"BSZ": "Operating Hours Counter",
"BT": "Bluetooth",
"BUEGEL": "Bracket",
"BUFFER": "Buffer",
"BUFFERS": "Buffers",
"BUILD": "Build",
"BUS": "Bus",
"BUSSE": "Buses",
"BUTTON": "Button",
"BY": "By",
"BYTE": "Byte",
"BYTES": "Bytes",
"BZW": "Respectively",
"CALC": "Calc",
"CALIB": "Calibration",
"CALIBRATE": "Calibrate",
"CALIBRATION": "Calibration",
"CALL": "Call",
"CAN": "CAN",
"CANFRAME": "CAN Frame",
"CAR": "Car",
"CARD": "Card",
"CAS": "Car Access System",
"CAS205": "Car Access System 205",
"CASSETTE": "Cassette",
"CASSETTENDECK": "Cassette Deck",
"CAT": "Catalyst",
"CBD": "CBD",
"CBS": "CBS Service",
"CCC": "Car Communication Computer",
"CD": "CD",
"CDC": "CD Changer",
"CENTER": "Center",
"CERT": "Certificate",
"CFL": "Cornering Fog Light",
"CHANGE": "Change",
"CHANNEL": "Channel",
"CHECK": "Check",
"CHECKCONTROL": "Check Control",
"CHECKSUM": "Checksum",
"CHECKSUMME": "Checksum",
"CHIP": "Chip",
"CHKSUM": "Checksum",
"CID": "CID",
"CKM": "Car Key Memory",
"CKMDATA": "CKM Data",
"CLAMP": "Clamp",
"CLEAR": "Clear",
"CLIPPING": "Clipping",
"CLR": "Clear",
"CLUTCH": "Clutch",
"CMD": "Command",
"CO": "CO",
"CO2": "CO2",
"COD": "Coding",
"CODDATA": "Coding Data",
"CODE": "Code",
"CODEDATA": "Code Data",
"CODES": "Codes",
"CODIER": "Coding",
"CODIERBITS": "Coding Bits",
"CODIERBLOCK": "Coding Block",
"CODIERDATA": "Coding Data",
"CODIERDATEN": "Coding Data",
"CODIEREN": "Coding",
"CODIERSTATUS": "Coding Status",
"CODIERUNG": "Coding",
"CODING": "Coding",
"CODINGRELEVANT": "Coding Relevant",
"COLOR": "Color",
"COMFORT": "Comfort",
"COMM": "Comm",
"COMMON": "Common",
"COMMUNICATION": "Communication",
"COMPILER": "Compiler",
"COMPLETE": "Complete",
"COMPLETION": "Completion",
"COMPONENT": "Component",
"CONFIG": "Config",
"CONFIGURATION": "Configuration",
"CONNECTED": "Connected",
"CONNECTION": "Connection",
"CONNTABLE": "Connection Table",
"CONS": "Console",
"CONTACTBOOK": "Contact Book",
"CONTR": "Control",
"CONTROL": "Control",
"CONTROLFELD": "Control Field",
"CONTROLLER": "Controller",
"COOKIES": "Cookies",
"COPY": "Copy",
"CORR": "Correction",
"CORRECTION": "Correction",
"COTOOL": "Coding Tool",
"COUNT": "Count",
"COUNTER": "Counter",
"COUNTS": "Counts",
"CPU": "CPU",
"CRASH": "Crash",
"CRASHDATEN": "Crash Data",
"CRC": "CRC",
"CREATE": "Create",
"CRU": "CRU",
"CRUISE": "Cruise",
"CS": "Checksum",
"CTRL": "Control",
"CURRENT": "Current",
"CURRENTUIFDATATABLE": "Current UIF Data Table",
"CVT": "CVT",
"DAB": "Digital Audio Broadcasting",
"DAC": "DAC",
"DAEMPFERPROG": "Damper Program",
"DATA": "Data",
"DATE": "Date",
"DATEI": "File",
"DATENINDEX": "Data Index",
"DATENSATZ": "Data Record",
"DATENSATZNUMMER": "Dataset Number",
"DATENVERKEHR": "Data Traffic",
"DATUM": "Date",
"DAUERAUS": "Permanent Off",
"DAUERLAUFDATEN": "Endurance Run Data",
"DC": "DC",
"DEAK": "Deactivate",
"DEAKTIVIEREN": "Deactivate",
"DEBUG": "Debug",
"DEBUGGING": "Debugging",
"DEFAULT": "Default",
"DEFAULTS": "Defaults",
"DEFEKTE": "Defects",
"DEFROST": "Defrost",
"DEGRADED": "Degraded",
"DEK": "Decode",
"DEL": "Delete",
"DELAY": "Delay",
"DELETE": "Delete",
"DELTA": "Delta",
"DEMAND": "Demand",
"DEMO": "Demo",
"DENORM": "Denormalize",
"DENORMIEREN": "Denormalize",
"DENORMIERER": "Denormalizer",
"DENORMIERUNGS": "Denormalization",
"DEPENDENT": "Dependent",
"DEPENDING": "Depending",
"DESULFATISIERUNG": "Desulfation",
"DETAIL": "Detail",
"DETECT": "Detect",
"DEVICE": "Device",
"DEVICES": "Devices",
"DEVIDS": "Device IDs",
"DFMONITOR": "Diagnostic Fault Monitor",
"DIAG": "Diagnostics",
"DIAGNOSE": "Diagnostic",
"DIAGNOSEBIT": "Diagnostic Bit",
"DIAGNOSEINDEX": "Diagnostic Index",
"DIAGNOSEMODE": "Diagnostic Mode",
"DIAGNOSEPROTOKOLL": "Diagnostic Log",
"DIAGNOSETESTBETRIEB": "Diagnostic Test Mode",
"DIAGNOSEWERTE": "Diagnostic Values",
"DIAGNOSIS": "Diagnosis",
"DIAGNOSTIC": "Diagnostic",
"DIAGNOSTICEND": "Diagnostic End",
"DIAGNOSTICS": "Diagnostics",
"DIAGSTAT": "Diagnostic Status",
"DIAGTUNNELLING": "Diagnostic Tunneling",
"DICHTHEIT": "Leak Tightness",
"DICKE": "Thickness",
"DIFF": "Diff",
"DIG": "Digital",
"DIGITAL": "Digital",
"DIGITAL1": "Digital 1",
"DIGITALEINGAENGE": "Digital Inputs",
"DIGITALSIGNALE": "Digital Signals",
"DILUTION": "Dilution",
"DIMM": "Dim",
"DIMMBELEUCHTUNG": "Dimmed Lighting",
"DIMMER": "Dimmer",
"DIMMWERT": "Dimming Value",
"DIR": "Direction",
"DIRECTION": "Direction",
"DIREKT": "Direct",
"DIS": "Display",
"DISA": "DISA Intake Flap",
"DISA2": "DISA 2",
"DISABLE": "Disable",
"DISC": "Disc",
"DISKRET": "Discrete",
"DISP": "Display",
"DISPLAY": "Display",
"DISPLAYBELEUCHTUNG": "Display Lighting",
"DISPLAYBEREICH": "Display Area",
"DISPLAYHELLIGKEIT": "Display Brightness",
"DISPLAYKONTRAST": "Display Contrast",
"DISPLAYLISTE": "Display List",
"DISPLAYTEST": "Display Test",
"DISTANCE": "Distance",
"DIVCALC": "Div Calc",
"DIVERSES": "Miscellaneous",
"DIVERSITY": "Diversity",
"DK": "Throttle",
"DK1": "Throttle Valve 1",
"DK2": "Throttle Valve 2",
"DKG": "Dual-Clutch Trans",
"DKHFM": "Throttle Air Mass Meter",
"DKP": "Throttle Position",
"DME": "DME",
"DME1": "DME 1",
"DME2": "DME 2",
"DME3": "Engine Control 3",
"DME4": "DME 4",
"DME5": "DME 5",
"DMTL": "Tank Leak Module",
"DMTLP": "Tank Leak Pump",
"DMTLV": "Tank Leak Module Valve",
"DOWN": "Down",
"DOWNLOAD": "Download",
"DPRAM": "Dual-Port RAM",
"DREHGEBER": "Rotary Encoder",
"DREHKNOPF": "Rotary Knob",
"DREHMOMENT": "Torque",
"DREHRATE": "Yaw Rate",
"DREHSINN": "Rotation Direction",
"DREHZ": "Speed",
"DREHZAHLFUEHLER": "Speed Sensor",
"DRIVE": "Drive",
"DRIVER": "Driver",
"DRIVERS": "Drivers",
"DRIVING": "Driving",
"DROSSELKLAPPE": "Throttle Valve",
"DRUCKRAMPE": "Pressure Ramp",
"DRUCKSENSOR": "Pressure Sensor",
"DRUCKSENSORSENSOR": "Pressure Sensor",
"DRUCKWERTE": "Pressure Values",
"DSC": "Dynamic Stability Control",
"DSP": "Digital Signal Processor",
"DTC": "DTC",
"DUMMY": "Dummy",
"DVD": "DVD",
"DWA": "Alarm System",
"DWG": "Wheel Speed Sensor",
"DWS": "Wheel Rotation Monitor",
"DXC": "Dynamic Stability",
"DYN": "Dynamic",
"DYNAMIK": "Dynamics",
"DYNAMISCH": "Dynamic",
"DYNAMISCHE": "Dynamic",
"DYNBLOCK": "Dynamic Block",
"E46": "E46",
"EA": "Input Output",
"EBL": "E-Box Fan",
"ECHTZEITDATEN": "Real-Time Data",
"ECO": "Eco",
"ECOS": "ECOS",
"ECOSERVO": "Eco Servo",
"ECU": "ECU",
"ECUHWVERSION": "ECU HW Version",
"EDC": "Electronic Damper Control",
"EDIC": "EDIC",
"EDR": "Event Data Recorder",
"EE": "EEPROM",
"EEP": "EEPROM",
"EEPROM": "EEPROM",
"EGAS": "Electronic Throttle",
"EGS": "Transmission Control",
"EGS1": "Transmission Control 1",
"EGS169": "Transmission Control 169",
"EICHLAUF": "Calibration Run",
"EIGEN": "Self",
"EIN": "On",
"EINBREMS": "Brake-In",
"EINBREMSEN": "Brake-In",
"EINBREMSPROZEDUR": "Brake-In Procedure",
"EINFACH": "Simple",
"EINFAHR": "Break-In",
"EINGAENGE": "Inputs",
"EINGANGE": "Inputs",
"EINGANGSSIGNALE": "Input Signals",
"EINKUPPELZEITEN": "Clutch Engagement Times",
"EINLASS": "Intake",
"EINLAUFSCHUTZ": "Run-In Protection",
"EINLEGEN": "Engage",
"EINLERNEN": "Adaptation",
"EINLERNVORGAENGE": "Teach-In Procedures",
"EINREGELZEIT": "Settling Time",
"EINSCHALTEN": "Switch On",
"EINSCHALTVERSUCHE": "Power-On Attempts",
"EINSPRITZ": "Injection",
"EINSPRITZMENGE": "Injection Quantity",
"EINSPRITZZEIT": "Injection Time",
"EINSTELLEN": "Adjust",
"EINSTELLUNG": "Setting",
"EINSTELLUNGEN": "Settings",
"EINZELADRESIERUNG": "Single Addressing",
"EINZELADRESSIERUNG": "Single Addressing",
"EINZELN": "Individual",
"EJECT": "Eject",
"EKP": "Fuel Pump",
"EKS": "Electronic Steering Lock",
"EL": "Electric",
"ELEKTRISCHE": "Electrical",
"ELEMENTS": "Elements",
"ELV": "Steering Column Lock",
"ELVCOUNTER": "Steering Lock Counter",
"EMERGENCY": "Emergency",
"EMF": "Park Brake",
"EMF1": "Parking Brake 1",
"EMF2": "Parking Brake 2",
"EML": "Electronic Throttle",
"EMPF": "Reception",
"EMPFANG": "Reception",
"EMPFINDLICHKEIT": "Sensitivity",
"ENABLE": "Enable",
"ENCODER": "Encoder",
"END": "End",
"ENDANSCHLAG": "End Stop",
"ENDE": "End",
"ENDTEST": "Final Test",
"ENERGIEMODE": "Energy Mode",
"ENERGIESPAR": "Energy Saving",
"ENERGIESPARMODE": "Energy Saving Mode",
"ENERGIESPARMODUS": "Energy Saving Mode",
"ENERGY": "Energy",
"ENGINE": "Engine",
"ENGINE1": "Engine 1",
"ENGINE2": "Engine 2",
"ENGINE3": "Engine 3",
"ENGINE4": "Engine 4",
"ENGINE5": "Engine 5",
"ENGINE7": "Engine 7",
"ENGINE9": "Engine 9",
"ENSEMBLE": "Ensemble",
"ENTFROSTUNG": "Defrost",
"ENTLUEFTEN": "Bleed",
"ENTLUEFTUNG": "Bleeding",
"ENTPRELLT": "Debounced",
"ENTRIEGELN": "Unlock",
"ENTWICKLERBOTSCHAFTEN": "Developer Messages",
"ENTWICKLUNG": "Development",
"EOL": "EOL",
"EPS": "Electric Power Steering",
"ER": "Recognition",
"ERASE": "Erase",
"ERGEBNIS": "Result",
"ERGEBNISSE": "Results",
"ERHALTEN": "Received",
"ERHOEHEN": "Increase",
"ERKENNUNG": "Detection",
"ERKENNUNGSMODUS": "Detection Mode",
"ERRCODE": "Error Code",
"ERROR": "Error",
"ERSATZPROGRAMME": "Replacement Programs",
"ERWEITERT": "Extended",
"ESN": "ESN",
"ETHERNET": "Ethernet",
"EV": "Solenoid Valve",
"EV1": "Injector Cyl. 1",
"EV2": "Injector Cyl. 2",
"EV3": "Injector Cyl. 3",
"EV4": "Injector Cyl. 4",
"EV5": "Injector Cyl. 5",
"EV6": "Injector Cyl. 6",
"EVAP": "EVAP",
"EVAUSBL": "EVAP Shutoff",
"EVENT": "Event",
"EWS": "Immobilizer",
"EWS4": "Immobilizer",
"EX": "Exhaust",
"EXECUTE": "Execute",
"EXIT": "Exit",
"EXPERT": "Expert",
"EXT": "External",
"EXTENDED": "Extended",
"EXTERNAL": "External",
"EXTRA": "Extra",
"EXTRAHIEREN": "Extract",
"FA": "Vehicle Order",
"FACTORY": "Factory",
"FADER": "Fader",
"FAHR": "Drive",
"FAHREN": "Drive",
"FAHRER": "Driver",
"FAHRERLENKWINKEL": "Driver Steering Angle",
"FAHRGESTELL": "Chassis",
"FAHRGESTELLNUMMER": "Chassis Number",
"FAHRMODUSZAEHLER": "Drive Mode Counter",
"FAHRPEDALWINKEL": "Accelerator Pedal Angle",
"FAHRZEUG": "Vehicle",
"FAHRZEUGAUFTRAG": "Vehicle Order",
"FAHRZEUGGESCHWINDIGKEITEN": "Vehicle Speeds",
"FAHRZEUGHOEHE": "Vehicle Height",
"FAHRZEUGNEIGUNG": "Vehicle Tilt",
"FAHRZEUGTESTER": "Vehicle Tester",
"FAHRZEUGTYP": "Vehicle Type",
"FAHRZYKLUSZAEHLER": "Drive Cycle Counter",
"FAKTOR": "Factor",
"FALLBACK": "Fallback",
"FALSE": "False",
"FAN": "Fan",
"FARBFLAECHE": "Color Area",
"FASTA": "FASTA",
"FASTA2": "FASTA2",
"FASTFILTER": "Fast Filter",
"FAULT": "Fault",
"FAULTDETECTION": "Fault Detection",
"FB": "Function Block",
"FBD": "Remote Key",
"FBLOCK": "Function Block",
"FBLOCKS": "Function Blocks",
"FCAN": "F-CAN",
"FEHLERSPEICHER": "Fault Memory",
"FEHLERZUSTAENDE": "Fault States",
"FEINLECKMESSUNG": "Fine Leak Measurement",
"FELDSTAERKE": "Field Strength",
"FENSTER": "Window",
"FENSTERHEBER": "Window Lifter",
"FENSTERHEBERLAUF": "Window Lifter Run",
"FERNLICHT": "High Beam",
"FERTIG": "Done",
"FERTIGUNG": "Production",
"FERTIGUNGSDATEN": "Production Data",
"FERTIGUNGSDATUM": "Production Date",
"FESTELLKRAFT": "Clamping Force",
"FESTSTELL": "Parking Brake",
"FESTSTELLEN": "Detect",
"FESTSTELLKRAFT": "Clamping Force",
"FESTSTELLVORGAENGE": "Parking Operations",
"FG": "Vehicle",
"FGNR": "Chassis Number",
"FGR": "Cruise Control",
"FGRL": "Cruise Control Lamp",
"FGRMOT": "Cruise Control Motor",
"FGRPOT": "Cruise Control Potentiometer",
"FH": "Window Lifter",
"FILE": "File",
"FILTER": "Filter",
"FILTERWERTE": "Filter Values",
"FIND": "Find",
"FIRMWARE": "Firmware",
"FIX": "Fix",
"FL": "Front Left",
"FLA": "High Beam Assistant",
"FLAG": "Flag",
"FLAGS": "Flags",
"FLANKENADAPTION": "Edge Adaptation",
"FLAP": "Flap",
"FLARE": "Flare",
"FLASHABLE": "Flashable",
"FLOTTENMODUS": "Fleet Mode",
"FM": "FM",
"FOERDERMENGE": "Delivery Quantity",
"FOND": "Rear Compartment",
"FONDGEBLAESE": "Rear Blower",
"FONDKLIMA": "Rear Climate Control",
"FONDRAUM": "Rear Compartment",
"FOR": "For",
"FORMAT": "Format",
"FORTFUEHREN": "Continue",
"FORTSETZEN": "Continue",
"FOTOZELLE": "Photocell",
"FP": "Fuel Pump",
"FR": "Front Right",
"FRAME": "Frame",
"FREEZE": "Freeze",
"FREEZEFRAME": "Freeze Frame",
"FREI": "Free",
"FREIGABE": "Release",
"FREIGABEZAEHLER": "Enable Counter",
"FREIGEBEN": "Enable",
"FREISCHALTUNG": "Activation",
"FREQUENCY": "Frequency",
"FREQUENZ": "Frequency",
"FREQUENZBAND": "Frequency Band",
"FRIENDLY": "Friendly",
"FRISCHLUFT": "Fresh Air",
"FROM": "From",
"FRONT": "Front",
"FRUEH": "Early",
"FUEL": "Fuel",
"FUELLMODUS": "Fill Mode",
"FUELTANK": "Fuel Tank",
"FUNC": "Function",
"FUNCTION": "Function",
"FUNKSCHLUESSEL": "Remote Key",
"FUNKTION": "Function",
"FUNKTIONAL": "Functional",
"FUNKTIONEN": "Functions",
"FUNKTIONS": "Functional",
"FUNKTIONSANZEIGE": "Function Display",
"FUNKTIONSBELEUCHTUNG": "Function Lighting",
"FUNKTIONSERGEBNISSE": "Function Results",
"FUNKTIONSPRUEFUNG": "Function Test",
"FUNKTIONSSTATI": "Function Status",
"FUNKTIONSTEST": "Function Test",
"FUSSHEBELFEHLBEDIENUNG": "Pedal Misuse",
"FUSSHEBELFEHLBETAETIGUNG": "Pedal Misoperation",
"FUSSRAUM": "Footwell",
"FW": "Firmware",
"FWV": "Firmware Version",
"FZ": "Vehicle",
"FZD": "Roof Function Center",
"FZE": "Vehicle Electronics",
"FZG": "Vehicle",
"FZM": "Vehicle Center Module",
"GAENGE": "Gears",
"GAIN": "Gain",
"GAL": "Speed Volume",
"GANGANZEIGE": "Gear Display",
"GANGWAHL": "Gear Selection",
"GASPEDAL": "Accelerator Pedal",
"GATEWAY": "Gateway",
"GATEWAYMODULES": "Gateway Modules",
"GATEWAYTABELLE": "Gateway Table",
"GAUGE": "Gauge",
"GAUGES": "Gauges",
"GEAR": "Gear",
"GEBER": "Sensor",
"GEBERRAD": "Sensor Wheel",
"GEBL": "Blower",
"GEBLAESE": "Blower",
"GEBLREGLER": "Blower Controller",
"GEDRUECKT": "Pressed",
"GELB": "Yellow",
"GEN": "Generator",
"GENERAL": "General",
"GENERATE": "Generate",
"GENERATOR": "Alternator",
"GENERIEREN": "Generate",
"GENINFO": "General Info",
"GENTEX": "Gentex",
"GERAETE": "Devices",
"GERAETEADRESSE": "Device Address",
"GERAETEDATEN": "Device Data",
"GERAETESUCHE": "Device Search",
"GERUCHSSTARTVERRIEGELUNG": "Odor Start Lock",
"GESAMT": "Total",
"GESCH": "Speed",
"GESCHWINDIGKEIT": "Speed",
"GESCHWINDIGKEITEN": "Speeds",
"GESPERRT": "Locked",
"GET": "Get",
"GETAKTET": "Clocked",
"GETDEFAULTREGISTRY": "Get Default Registry",
"GETR": "Transmission",
"GETRIEBEAUSGANGSDREHZAHL": "Transmission Output Speed",
"GETRIEBECODE": "Transmission Code",
"GETRIEBEDATEN": "Transmission Data",
"GETRIEBEEINGANGSDREHZAHL": "Transmission Input Speed",
"GETRIEBEPOSITION": "Gear Position",
"GETRIEBETEMP": "Transmission Temp",
"GETRIEBETEMPERATUR": "Transmission Temperature",
"GETTICKCOUNT": "Get Tick Count",
"GIERRATEN": "Yaw Rates",
"GIERRATENEMPFINDLICHKEIT": "Yaw Rate Sensitivity",
"GLF": "Radiator Shutter",
"GLOBAL": "Global",
"GLOBALFLG": "Global Flag",
"GLOBALVAR": "Global Variable",
"GLUEH": "Glow",
"GM": "Body Module",
"GM3": "Body Module 3",
"GONG": "Chime",
"GPS": "GPS",
"GRACENOTES": "Gracenotes",
"GRAD": "Degrees",
"GRAPHICS": "Graphics",
"GRIDVERSCHIEBUNG": "Grid Shift",
"GROBLECK": "Gross Leak",
"GROBLECKMESSUNG": "Coarse Leak Measurement",
"GRUEN": "Green",
"GURTBRINGER": "Belt Presenter",
"GURTKONTAKTE": "Belt Contacts",
"GW": "Gateway",
"GWS": "Gear Selector Switch",
"GYRO": "Gyro",
"GYROSIGNAL": "Gyro Signal",
"HA": "Rear Axle",
"HAFTSYSTEM": "Adhesion System",
"HALL": "Hall Sensor",
"HALLSENSOREN": "Hall Sensors",
"HALTE": "Hold",
"HALTEN": "Hold",
"HANDBREMSE": "Handbrake",
"HANDJUSTAGE": "Manual Adjustment",
"HANDSENDER1": "Remote Transmitter 1",
"HANDSENDER2": "Remote Key 2",
"HAPTIC": "Haptic",
"HARD": "Hard",
"HARDWARENUMMER": "Hardware Number",
"HARDWARESTERNNUMMER": "Hardware Star Number",
"HARDWARETEST": "Hardware Test",
"HARDWAREVERSION": "Hardware Version",
"HAUPTDRUCK": "Main Pressure",
"HAZARD": "Hazard",
"HDD": "Hard Disk Drive",
"HDDOWNLOAD": "HDD Download",
"HEADER": "Header",
"HEADING": "Heading",
"HEADROOM": "Headroom",
"HEATER": "Heater",
"HEBEL": "Lever",
"HECKROLLO": "Rear Sunshade",
"HECKSCHEIBE": "Rear Window",
"HECKSCHEIBEN": "Rear Windows",
"HEIGHT": "Height",
"HEIZBARE": "Heatable",
"HEIZUNG": "Heating",
"HELBAKO": "Helbako",
"HELLIGKEIT": "Brightness",
"HERSTELLDATEN": "Manufacturing Data",
"HERSTELLDATUM": "Manufacturing Date",
"HERSTELLER": "Manufacturer",
"HERSTELLERDATEN": "Manufacturer Data",
"HERSTELLERTEST": "Manufacturer Test",
"HERSTELLINFO": "Manufacturing Info",
"HEX": "Hex",
"HFM": "Air Mass Meter",
"HFMS": "Hot Film Air Mass Sensor",
"HIGHLEVEL": "High Level",
"HIGHSYNCCONNECTION": "High Sync Connection",
"HINTEN": "Rear",
"HISTOGRAM": "Histogram",
"HISTORIE": "History",
"HISTORIENSPEICHER": "History Memory",
"HISTORIESPEICHER": "History Memory",
"HISTORY": "History",
"HK": "Heating",
"HLS1": "Oxygen Sensor Heater 1",
"HLS2": "Oxygen Sensor Heater 2",
"HLS3": "Oxygen Sensor Heater 3",
"HLS4": "Oxygen Sensor Heater 4",
"HMI": "HMI",
"HOCHLAUFPRUEFUNG": "Startup Test",
"HOCHSCHALTEN": "Upshift",
"HOEHE": "Altitude",
"HOEHENSTAND": "Ride Height",
"HORIZONTAL": "Horizontal",
"HS": "High Side",
"HUB": "Stroke",
"HUD": "Head-Up Display",
"HUPE": "Horn",
"HW": "Hardware",
"HWNR": "Hardware Number",
"HYDRAULIK": "Hydraulics",
"HYDRAULIKPUMPE": "Hydraulic Pump",
"HYDRO": "Hydro",
"I2C": "I2C",
"IBOC": "In-Band On-Channel",
"IBS": "Battery Sensor",
"ID": "ID",
"IDENTIFIKATION": "Identification",
"IG": "Ignition",
"IGN": "Ignition",
"IGR": "Idle Speed Control",
"IHKA": "Automatic Climate Control",
"ILLUMINATION": "Illumination",
"IMAALLE": "IMA All",
"IMAGE": "Image",
"IMOB": "Immobilizer",
"IMOTOR": "Engine Current",
"IMPEDANZMESSUNG": "Impedance Measurement",
"IMPULS": "Pulse",
"IN": "Input",
"INAKTIVEREIGNIS1": "Inactive Event 1",
"INAKTIVEREIGNIS2": "Inactive Event 2",
"INAKTIVEREIGNIS3": "Inactive Event 3",
"INBETRIEBNAHME": "Commissioning",
"INCLINATION": "Inclination",
"INCLUDED": "Included",
"INCREASE": "Increase",
"INDEX": "Index",
"INDIKATOR": "Indicator",
"INDIVIDUALDATA": "Individual Data",
"INDIVIDUALISIERUNG": "Individualization",
"INFORMATION": "Information",
"INFOSPEICHER": "Info Memory",
"INI": "Init",
"INIT": "Init",
"INITIALISATION": "Initialization",
"INITIALISIERUNG": "Initialization",
"INITIALIZATION": "Initialization",
"INJ": "Injector",
"INJECTION": "Injection",
"INJECTOR": "Injector",
"INJEKTION": "Injection",
"INK": "Increment",
"INKREMENT": "Increment",
"INKREMENTE": "Increments",
"INNENBELEUCHTUNG": "Interior Lighting",
"INNENFUEHLERGEBLAESE": "Interior Sensor Blower",
"INNENLICHT": "Interior Light",
"INNENTEMP": "Interior Temperature",
"INNENTEMPERATUR": "Interior Temperature",
"INPA": "INPA",
"INPUT": "Input",
"INPUTPEGEL": "Input Level",
"INPUTS": "Inputs",
"INSTR2": "Instrument 2",
"INSTR3": "Instrument 3",
"INT": "Internal",
"INTEGRATOR": "Integrator",
"INTEGRATOREN": "Integrators",
"INTERFACETYPE": "Interface Type",
"INTERN": "Internal",
"INTERNAL": "Internal",
"INTERNE": "Internal",
"INTERNER": "Internal",
"INTERRUPT": "Interrupt",
"INVALID": "Invalid",
"IO": "OK",
"IODIGITAL": "IO Digital",
"IOSTATES": "IO States",
"IP": "IP",
"IPCONFIG": "IP Config",
"IS": "Actual",
"ISN": "ISN",
"ISO14229": "ISO 14229",
"IST": "Actual",
"ISTGANG": "Actual Gear",
"ISTKRAFT": "Actual Force",
"ISTLAGE": "Actual Position",
"ISTPOSITION": "Actual Position",
"ISTSTAND": "Actual Level",
"ISTUFE": "Integration Level",
"ISTWERTE": "Actual Values",
"ISTZUSTAND": "Actual State",
"JITTERMESSUNG": "Jitter Measurement",
"JOBS": "Jobs",
"JUSTAGEDATEN": "Adjustment Data",
"JUSTAGEKENNLINIE": "Adjustment Curve",
"JUSTIERUNG": "Adjustment",
"KAELTEMITTELVERDICHTER": "Refrigerant Compressor",
"KALIBRATION": "Calibration",
"KALIBRIERDATEN": "Calibration Data",
"KALIBRIEREREIGNIS1": "Calibration Event 1",
"KALIBRIERSTATUS": "Calibration Status",
"KALIBRIERUNG": "Calibration",
"KALIBRIERWERTE": "Calibration Values",
"KALTABFRAGE": "Cold Query",
"KALTBEFEUERUNG": "Cold Firing",
"KALTLUFT": "Cold Air",
"KANAELE": "Channels",
"KANAL": "Channel",
"KATALYSATOR": "Catalytic Converter",
"KATS": "Catalytic Converters",
"KBUS": "K-Bus",
"KBUSADRESSE": "K-Bus Address",
"KD": "Service",
"KENNFELDTHERMOSTAT": "Map Thermostat",
"KENNLINIE": "Characteristic Curve",
"KENNLINIEN": "Characteristic Curves",
"KENNUNG": "Identifier",
"KENNZEICHEN": "License Plate",
"KENNZEICHENLEUCHTE": "License Plate Light",
"KEY": "Key",
"KF": "Map",
"KFK": "Map Cooling",
"KFZ": "Vehicle",
"KI": "Instrument Cluster",
"KICKDOWN": "Kickdown",
"KILOMETERSTAND": "Odometer",
"KINDERSICHERUNG": "Child Lock",
"KK": "KK",
"KL": "Terminal",
"KL15": "Terminal 15",
"KL15W": "Terminal 15W",
"KL30": "Terminal 30",
"KL50": "Terminal 50",
"KLANGZEICHEN": "Sound Signal",
"KLAPPEN": "Flaps",
"KLAPPENPOSITION": "Flap Position",
"KLAPPTOP": "Convertible Top",
"KLASSIERSPEICHER": "Classification Memory",
"KLEMME": "Terminal",
"KLEMMEN": "Terminals",
"KLEMMENSPANNUNG": "Terminal Voltage",
"KLIMA": "Climate",
"KLIMAGERAETETYP": "AC Unit Type",
"KLIMASYSTEM": "Climate System",
"KLOPF": "Knock",
"KLOPFEN": "Knocking",
"KLOPFREGELUNG": "Knock Control",
"KLSTRG": "Climate Control",
"KM": "Kilometers",
"KODIERDATEN": "Coding Data",
"KOE": "KOE",
"KOMBI": "Instrument Cluster",
"KOMFORT": "Comfort",
"KOMFORTFUNKTION": "Comfort Function",
"KOMMUNIKATION": "Communication",
"KOMMUNIKATIONSTEST": "Communication Test",
"KOMP": "Compressor",
"KOMPLETT": "Complete",
"KOMPONENTEN": "Components",
"KOMPRESSOR": "Compressor",
"KOMPRESSORVENTIL": "Compressor Valve",
"KONFIGURATION": "Configuration",
"KONFIGURIEREN": "Configure",
"KOPF": "Head",
"KOPPELFEDER": "Coupling Spring",
"KOREL": "A/C Compressor Relay",
"KORREKTUR": "Correction",
"KORREKTURFAKTOR": "Correction Factor",
"KR": "Knock Control",
"KRAFTEINSATZ": "Force Application",
"KRAFTSENSOR": "Force Sensor",
"KRAFTSTOFFDRUCK": "Fuel Pressure",
"KRAFTSTOFFPUMPE": "Fuel Pump",
"KRAFTSTOFFTEMPERATUR": "Fuel Temp",
"KTEST": "Component Test",
"KU": "KU",
"KUEHLFACH": "Cooling Compartment",
"KUEHLMITTELSTAND": "Coolant Level",
"KUEHLMITTELTEMPERATUR": "Coolant Temp",
"KUEHLW": "Coolant",
"KUGELAUS": "Ball Disengage",
"KUP": "Clutch",
"KUPP": "Clutch",
"KUPPLUNG": "Clutch",
"KUPPLUNGS": "Clutch",
"KUPPLUNGSCHARAKTERISTIK": "Clutch Characteristic",
"KUPPLUNGSEINLERNWERTE": "Clutch Adaptation Values",
"KUPPLUNGSKENNLINIE": "Clutch Curve",
"KUPPLUNGSPOSITION": "Clutch Position",
"KUPPLUNGSSCHLEIFPUNKT": "Clutch Engagement Point",
"KUPPVENTIL": "Clutch Valve",
"KURVE": "Curve",
"KURZHUB": "Short Stroke",
"KURZSCHLUSS": "Short Circuit",
"KVA": "Fuel Quantity Adjustment",
"KW": "Crankshaft",
"KWP": "Keyword Protocol",
"LADE": "Charge",
"LADEDRUCK": "Boost Pressure",
"LADER": "Charger",
"LADEZYCLEN": "Charge Cycles",
"LAENDERFAKTOR": "Country Factor",
"LAENDERVARIANTE": "Country Variant",
"LAENGE": "Length",
"LAENGS": "Longitudinal",
"LAENGSBESCHLEUNIGUNG": "Longitudinal Acceleration",
"LAGE": "Position",
"LAMBDASONDEN": "Oxygen Sensors",
"LAMELLEN": "Louvers",
"LAMPE": "Lamp",
"LAMPEN": "Lamps",
"LAMPENAUSGANG": "Lamp Output",
"LANG": "Long",
"LANGUAGE": "Language",
"LANGZEITABGLEICH": "Long-Term Calibration",
"LAST": "Load",
"LASTPROFIL": "Load Profile",
"LASTSIGNAL": "Load Signal",
"LASTWECHSEL": "Load Change",
"LASTWSENSOR": "Load Sensor",
"LAUFUNRUHE": "Misfire",
"LAUFWERK": "Drive",
"LAUTSPRECHER": "Speaker",
"LAYER": "Layer",
"LCD": "LCD",
"LDP": "Leak Diagnosis Pump",
"LEAR": "Learn",
"LEARN": "Learn",
"LECK": "Leak",
"LECKAGEWERT": "Leakage Value",
"LECKLUFT": "Leak Air",
"LED": "LED",
"LEDS": "LEDs",
"LEERLAUF": "Idle",
"LEERLAUFINTEGRATOR": "Idle Integrator",
"LEERLAUFLUFT": "Idle Air",
"LEFT": "Left",
"LEHNE": "Backrest",
"LEHNENKOPF": "Backrest Head",
"LEISE": "Quiet",
"LEISTUNGSSTUFE": "Power Stage",
"LEITUNG": "Line",
"LEITUNGSBEFUELLUNG": "Line Filling",
"LEMINFO": "LEM Info",
"LENGTH": "Length",
"LENKRAD": "Steering Wheel",
"LENKRADHEIZUNG": "Steering Wheel Heating",
"LENKRADSCHALTUNG": "Steering Wheel Shift",
"LENKRADWINKEL": "Steering Wheel Angle",
"LENKSAEULE": "Steering Column",
"LENKSEITE": "Steering Side",
"LENKSTOCK": "Steering Column Switch",
"LENKWINKEL": "Steering Angle",
"LENKWINKELOFFSET": "Steering Angle Offset",
"LENKWINKELSENSOR": "Steering Angle Sensor",
"LERNEN": "Learn",
"LERNFUNKTION": "Learning Function",
"LERNWERT": "Learned Value",
"LERNWERTE": "Learned Values",
"LESE": "Read",
"LESEN2": "Read 2",
"LESESTATISTIK": "Read Statistics",
"LESSEN": "Read",
"LETZTE": "Last",
"LETZTEN": "Last",
"LEUCHTE": "Lamp",
"LEUCHTEN": "Lamps",
"LEVEL": "Level",
"LEVELS": "Levels",
"LEVELUP": "Level Up",
"LEWI": "Steering Angle",
"LH": "Air Mass Meter",
"LHZ": "Auxiliary Heater",
"LI": "Left",
"LIBELLE1": "Level Bubble 1",
"LIBELLE2": "Level Bubble 2",
"LICENSE": "License",
"LICHT": "Light",
"LICHTQUELLEN": "Light Sources",
"LICHTTASTER": "Light Switch",
"LIEFEREANTENNUMMER": "Supplier Part Number",
"LIGHT": "Light",
"LIH": "LIH",
"LIMIT": "Limit",
"LIN": "LIN Bus",
"LINEAR": "Linear",
"LINEARSENSOREN": "Linear Sensors",
"LINES": "Lines",
"LINK": "Link",
"LINKS": "Left",
"LIST": "List",
"LISTE": "List",
"LL": "Idle",
"LLABG": "Idle Adjustment",
"LLDATENRETTUNG": "Idle Data Recovery",
"LLERH": "Idle Speed Increase",
"LLFS": "Idle Control",
"LLR": "Idle Speed Controller",
"LLSTELLER": "Idle Actuator",
"LM": "Air Mass",
"LMM": "Air Mass Meter",
"LOADING": "Loading",
"LOCAL": "Local",
"LOCALID": "Local ID",
"LOCATION": "Location",
"LOCK": "Lock",
"LOCKSTATE": "Lock State",
"LOES": "Delete",
"LOESEKRAFT": "Release Force",
"LOESEPOS": "Release Position",
"LOG": "Log",
"LOGGER": "Logger",
"LOGIN": "Login",
"LOGIN2": "Login 2",
"LOGISTIC": "Logistic",
"LONG": "Long",
"LOOP": "Loop",
"LOSSES": "Losses",
"LOUDNESS": "Loudness",
"LOUDSP": "Loudspeaker",
"LOWLEVEL": "Low Level",
"LOWTOL": "Low Tolerance",
"LS": "Oxygen Sensor",
"LSH": "Oxygen Sensor Heater",
"LSH3": "Lambda Heater 3",
"LSHK1H": "O2 Sensor Bank1 Heater",
"LSHK2H": "O2 Sensor Bank2 Heater",
"LSM": "Light Switch Module",
"LSVK1H": "O2 Sensor Pre-Cat Bank1 Heater",
"LSVK2H": "O2 Sensor Pre-Cat Bank2 Heater",
"LUEFTER": "Fan",
"LUEFTER1": "Fan 1",
"LUEFTER2": "Fan 2",
"LUFTBEDARF": "Air Demand",
"LUFTDRUCK": "Air Pressure",
"LUFTMASSE": "Air Mass",
"LUFTTEMP": "Air Temperature",
"LUFTTEMPERATUR": "Air Temperature",
"LV": "Front Left",
"LW": "Steering Angle",
"LWG": "Steering Angle Sensor",
"LWM": "Air Mass Sensor",
"LWR": "Headlight Range Control",
"LWS": "Steering Angle Sensor",
"MABIKI": "Thinning",
"MAC": "MAC",
"MAGNETVENTILE": "Solenoid Valves",
"MAINRELAIS": "Main Relay",
"MAN": "Manual",
"MANIPULATION": "Manipulation",
"MANIPULATIONS": "Manipulation",
"MANUELLER": "Manual",
"MANUFACTURER": "Manufacturer",
"MAP": "Map",
"MAPMATERIAL": "Map Material",
"MAPPINGS": "Mappings",
"MARGINAL": "Marginal",
"MASK": "Mask",
"MASKE": "Mask",
"MASSE": "Ground",
"MASTER": "Master",
"MASTERVIN": "Master VIN",
"MAXIMUM": "Maximum",
"MCGW": "Central Gateway",
"MD": "Torque",
"MDK": "Throttle Valve",
"MDK1": "Throttle 1",
"MDK2": "Throttle 2",
"MECH": "Mechanical",
"MECHANISCHER": "Mechanical",
"MEHRFACHSTARTWERTABGLEICH": "Multi Start Value Adjustment",
"MEM": "Memory",
"MEMO": "Memo",
"MEMORIES": "Memories",
"MEMORY": "Memory",
"MENGE": "Quantity",
"MENU": "Menu",
"MESS": "Measure",
"MESSAGE": "Message",
"MESSDATEN": "Measurement Data",
"MESSE": "Measure",
"MESSEMODE": "Measurement Mode",
"MESSSTRECKEN": "Measurement Sections",
"MESSUNG": "Measurement",
"MESSWERTBLOCK": "Measurement Block",
"MESSWERTE": "Measured Values",
"MESSWERTEBLOCK": "Measured Value Block",
"MFL": "Steering Wheel Controls",
"MFS": "Multifunction Steering Wheel",
"MICRO": "Micro",
"MICROPHONE": "Microphone",
"MID": "MID",
"MIKROSCHRITT": "Microstep",
"MIL": "MIL",
"MILAGE": "Mileage",
"MILE": "Mile",
"MIN": "Minute",
"MINUS": "Minus",
"MISC": "Misc",
"MISCHLUFT": "Mixed Air",
"MISLOCK": "Mislock",
"MIT": "With",
"MITTE": "Center",
"MITTELKON": "Center Console",
"MITTELWERTE": "Average Values",
"MIXER": "Mixer",
"MLFB": "Order Number",
"MMI": "MMI",
"MODEL": "Model",
"MODEWEITERSCHALTUNG": "Mode Switching",
"MODI": "Modes",
"MODIFICATION": "Modification",
"MODUL": "Module",
"MODULE": "Module",
"MODUS": "Mode",
"MOMENTENKENNLINIE": "Torque Characteristic Curve",
"MOMENTENSENSOR": "Torque Sensor",
"MONITOR": "Monitor",
"MONTAGE": "Assembly",
"MONTAGEBETRIEB": "Assembly Mode",
"MONTAGEMODE": "Assembly Mode",
"MONTAGEPOSITON": "Mounting Position",
"MOST": "MOST",
"MOSTDIAG": "MOST Diagnosis",
"MOSTREGISTER": "MOST Register",
"MOSTSYSTEM": "MOST System",
"MOT": "Engine",
"MOTORDREHZAHL": "Engine Speed",
"MOTOREN": "Motors",
"MOTORENDSTUFE": "Motor Output Stage",
"MOTORISTMOMENT": "Engine Actual Torque",
"MOTORLAGER": "Engine Mount",
"MOTORLAGEWINKEL": "Engine Position Angle",
"MOTORLAUFUNRUHE": "Engine Roughness",
"MOTORS": "Motors",
"MOTORSOLLMOMENT": "Engine Target Torque",
"MOTORSTROM": "Motor Current",
"MOTORTEMPERATUR": "Engine Temperature",
"MOTORTYP": "Engine Type",
"MPC": "Power Controller",
"MRSA": "Multiple Restraint System",
"MSA": "Auto Start-Stop",
"MSAINFO": "Auto Start-Stop Info",
"MUL": "Multiplexer",
"MULTIFUNKTION": "Multifunction",
"MULTIFUSES": "Multi Fuses",
"MUTE": "Mute",
"MV": "Solenoid Valve",
"MW": "Measured Value",
"MW5": "Measured Value 5",
"MWB": "Measured Value Block",
"NACHEINANDER": "Sequential",
"NACHRICHT": "Message",
"NACHSPANN": "Re-Tension",
"NACHZIEHEN": "Retighten",
"NAECHSTE": "Next",
"NAME": "Name",
"NASSARMHEIZUNG": "Wiper Arm Heating",
"NAVDVDPIN": "Nav DVD PIN",
"NAVI": "Navigation",
"NAVICHECK": "Navigation Check",
"NAVIMAP": "Navigation Map",
"NAVIMETADB": "Navigation Metadata DB",
"NEIGUNG": "Tilt",
"NETZWERK": "Network",
"NEU": "New",
"NEUE": "New",
"NEUFAHRZEUG": "New Vehicle",
"NEUSTART": "Restart",
"NEUTRAL": "Neutral",
"NEWSEELAND": "New Zealand",
"NEXT": "Next",
"NF": "NF",
"NICHT": "Not",
"NKAT": "Main Catalyst",
"NL": "NL",
"NMAX": "Max Speed",
"NO": "No",
"NOCKENWELLE": "Camshaft",
"NOISE": "Noise",
"NORM": "Norm",
"NORM2": "Norm 2",
"NORM3": "Norm 3",
"NORM4": "Norm 4",
"NORMAL": "Normal",
"NORMALER": "Normal",
"NORMIERUNG": "Normalization",
"NOTENTRIEGELUNG": "Emergency Release",
"NOTENTRIEGELUNGEN": "Emergency Releases",
"NOTIFIED": "Notified",
"NOTLAUF": "Limp Mode",
"NOTOK": "Not OK",
"NOTRUF": "Emergency Call",
"NOX": "NOx",
"NOX1": "NOx 1",
"NTC": "NTC",
"NTSC": "NTSC",
"NULL": "Null",
"NULLEN": "Nulling",
"NULLGANG": "Neutral Gear",
"NULLGANGSENSOR": "Neutral Gear Sensor",
"NULLPUNKT": "Zero Point",
"NUM": "Number",
"NUMBER": "Number",
"NUMERISCH": "Numeric",
"NUMMERN": "Numbers",
"NUR": "Only",
"NW": "Camshaft",
"NWG": "Camshaft Sensor",
"OBD": "OBD",
"OBD2": "OBD2",
"OBDII": "OBD-II",
"OC3": "Occupant Detection",
"ODER": "Or",
"ODO": "Odometer",
"OEFFNEN": "Open",
"OELPUMPE": "Oil Pump",
"OELTEMP": "Oil Temp",
"OELTEMPERATUR": "Oil Temperature",
"OF": "Of",
"OFF": "Off",
"OFFROAD": "Offroad",
"OFFSETWERTE": "Offset Values",
"OHNE": "Without",
"OIL": "Oil",
"OK": "OK",
"OL": "Oil",
"OLD": "Old",
"OLDECU": "Old ECU",
"ON": "On",
"ONCE": "Once",
"ONLINE": "Online",
"OPERATING": "Operating",
"OR": "Or",
"ORANGE": "Orange",
"OUT": "Out",
"OUTPUT": "Output",
"OUTPUTPORT": "Output Port",
"OUTPUTS": "Outputs",
"OWN": "Own",
"PAGE": "Page",
"PAIRED": "Paired",
"PAL": "PAL",
"PALETTE": "Palette",
"PANEL": "Panel",
"PARALLELE": "Parallel",
"PARAM": "Parameter",
"PARAMETERS": "Parameters",
"PARAMETERSATZ": "Parameter Set",
"PARAMETERSATZ1": "Parameter Set 1",
"PARAMETERSATZ2": "Parameter Set 2",
"PARAMETRIERT": "Parameterized",
"PARKBREMSE": "Parking Brake",
"PASSIV": "Passive",
"PASSKEY": "Passkey",
"PASSWORT": "Password",
"PATCH": "Patch",
"PDC": "Park Distance Control",
"PEDALWERTGEBER": "Pedal Sensor",
"PER": "Per",
"PERFORMANCE": "Performance",
"PERIOD": "Period",
"PERMANENT": "Permanent",
"PERSISTENT": "Persistent",
"PERSISTENZ": "Persistence",
"PERSONALISIERUNG": "Personalization",
"PFAD": "Path",
"PHASENSPANNUNGEN": "Phase Voltages",
"PHASENSTROEME": "Phase Currents",
"PHONE": "Phone",
"PHY": "Physical Layer",
"PHYS": "Physical",
"PHYSICAL": "Physical",
"PHYSIKALISCH": "Physical",
"PICTURE": "Picture",
"PINS": "Pins",
"PLAUSIBILISIERUNG": "Plausibility Check",
"PLAUSICHECK": "Plausibility Check",
"PLAUSIWERTE": "Plausibility Values",
"PLIP": "Remote Unlock",
"PLUS": "Plus",
"PM": "PM",
"PMMODUS": "PM Mode",
"POI": "Point Of Interest",
"PORT": "Port",
"PORTS": "Ports",
"POS": "Position",
"POSITION": "Position",
"POSITIONSDATEN": "Position Data",
"POTENTIOMETER": "Potentiometer",
"POTI": "Potentiometer",
"POTI1": "Potentiometer 1",
"POTIANSCHLAEGE": "Potentiometer Stops",
"POTIS": "Potentiometers",
"POWER": "Power",
"POWERFOLLOWUP": "Power Follow-Up",
"POWERMANAGEMENT": "Power Management",
"PRAEPROZESSOR": "Preprocessor",
"PRE": "Pre",
"PRECALIB": "Pre-Calibration",
"PREH": "Preh",
"PRG": "Program",
"PRGDATE": "Program Date",
"PRIMAERSPEICHER": "Primary Memory",
"PRIOSTUFEN": "Priority Levels",
"PROD": "Production",
"PRODUCT": "Product",
"PRODUCTION": "Production",
"PROG": "Program",
"PROGRAM": "Program",
"PROGRAMM": "Program",
"PROGRAMMCODE": "Program Code",
"PROGRAMMERSTELLUNG": "Program Creation",
"PROGRAMMIERDATUM": "Programming Date",
"PROGRAMMIEREN": "Program",
"PROGRAMMING": "Programming",
"PROPORTIONAL": "Proportional",
"PROTOKOLL": "Protocol",
"PROVISIONING": "Provisioning",
"PRUEF": "Test",
"PRUEFEN": "Check",
"PRUEFMODUS": "Test Mode",
"PRUEFUNG": "Test",
"PSEUDO": "Pseudo",
"PTC": "PTC Heater",
"PTCAN": "Powertrain CAN",
"PULSE": "Pulse",
"PUMPE": "Pump",
"PUMPEN": "Pumps",
"PUMPENSTROM": "Pump Current",
"PUSHHOLD": "Push Hold",
"PWG": "Accelerator Pedal Sensor",
"PWG1": "Accelerator Pedal Sensor 1",
"PWG2": "Accelerator Pedal Sensor 2",
"PWM": "PWM",
"PWR": "Power",
"QLT": "Quality",
"QUADRANT": "Quadrant",
"QUALIFIER": "Qualifier",
"QUALITAET": "Quality",
"QUALITY": "Quality",
"QUARZABGLEICH": "Crystal Calibration",
"QUERBESCH": "Lateral Acceleration",
"QUERBESCHLEUNIGUNG": "Lateral Acceleration",
"QUICK": "Quick",
"QUICKTEST": "Quick Test",
"RAD": "Wheel",
"RADARZIEL": "Radar Target",
"RADELEKTRONIK": "Wheel Electronics",
"RADGESCHWINDIGKEIT": "Wheel Speed",
"RADGESCHWINDIGKEITEN": "Wheel Speeds",
"RADIO": "Radio",
"RADMOMENTEN": "Wheel Torques",
"RADSATZVARIANTE": "Wheelset Variant",
"RAILDRUCK": "Rail Pressure",
"RAM": "RAM",
"RAMDATA": "RAM Data",
"RAMPE": "Ramp",
"RATE": "Rate",
"RATIO": "Ratio",
"RATIOMETRISCHE": "Ratiometric",
"RATIOS": "Ratios",
"RAW": "Raw",
"RBM": "RBM",
"RBMMODE9": "RBM Mode 9",
"RDS": "RDS",
"RDU": "Tire Pressure",
"RE": "Right",
"READ": "Read",
"READABLE": "Readable",
"READBACKUPMEMORY": "Read Backup Memory",
"READECU": "Read ECU",
"READY": "Ready",
"REASON": "Reason",
"RECEIVE": "Receive",
"RECEIVER": "Receiver",
"RECEPTION": "Reception",
"RECHTS": "Right",
"RECIRC": "Recirculation",
"RECOG": "Recognition",
"REDUZIERT": "Reduced",
"REDUZIERTE": "Reduced",
"REF": "Reference",
"REFERENZLAUF": "Reference Run",
"REFLAGE": "Reference Position",
"REG": "Reg",
"REGELUNG": "Control",
"REGELUNGSDATEN": "Control Data",
"REGELUNGSWERTE": "Control Values",
"REGENSENSOR": "Rain Sensor",
"REGION": "Region",
"REGISTER": "Register",
"REGISTERS": "Registers",
"REGISTRIEREN": "Register",
"REGISTRY": "Registry",
"REGLER": "Controller",
"REGLERGROESSE": "Controller Variable",
"REGLERGROESSEN": "Controller Variables",
"REGLERPARAM": "Controller Parameters",
"REGLERWERTE": "Controller Values",
"REGULATOR": "Regulator",
"REICHWEITENSCHWELLE": "Range Threshold",
"RELAIS": "Relay",
"RELATIV": "Relative",
"REMOTE": "Remote",
"REP": "Rep",
"REPAIR": "Repair",
"REPEAT": "Repeat",
"REPORT": "Report",
"REPROG": "Reprogram",
"REQPOWERTRAINFREEZEFRAMEDATA": "Request Powertrain Freeze Frame",
"REQRAWMODE": "Request Raw Mode",
"REQUEST": "Request",
"REQUESTSEEDANDSENDKEY": "Request Seed Send Key",
"RESCUE": "Rescue",
"RESETPEICHER": "Reset Memory",
"RESETZAEHLER": "Reset Counter",
"RESTART": "Restart",
"RESTORE": "Restore",
"RESULT": "Result",
"RESULTS": "Results",
"RESYNC": "Resync",
"RET": "Return",
"RETURN": "Return",
"REV": "Rev",
"REVERSIEREN": "Reverse",
"REVERSIERER": "Reverser",
"REVERSIERUNGS": "Reversing",
"REVISION": "Revision",
"RF": "RF",
"RFK": "Rear View Camera",
"RGB": "RGB",
"RH": "Right",
"RICHTUNG": "Direction",
"RIGHT": "Right",
"RINGBELEUCHTUNG": "Ring Lighting",
"RINGBRUCH": "Ring Break",
"RINGBUF": "Ring Buffer",
"RINGBUFFER": "Ring Buffer",
"RINGSPEICHER": "Ring Buffer",
"RLS": "Rain Light Sensor",
"ROH": "Raw",
"ROHWERT": "Raw Value",
"ROHWERTE": "Raw Values",
"ROM": "ROM",
"ROT": "Red",
"ROTATION": "Rotation",
"ROTOR": "Rotor",
"ROTORLAGESENSOR": "Rotor Position Sensor",
"ROUTE": "Route",
"ROUTINE": "Routine",
"ROUTING": "Routing",
"RPA": "Tire Pressure Monitor",
"RR": "Rear Right",
"RSK": "RSK",
"RUECKFAHRLICHT": "Reverse Light",
"RUECKSETZEN": "Reset",
"RUECKWAERTS": "Reverse",
"RUECKWAERTSGANG": "Reverse Gear",
"RUHESTROMMESSUNG": "Quiescent Current Measurement",
"RUHESTROMUEBERWACHUNG": "Quiescent Current Monitoring",
"RUHESTROMWECKZAEHLER": "Quiescent Current Wake Counter",
"RUNTERSCHALTEN": "Downshift",
"RV": "RV",
"RX": "Receive",
"SAEULE": "Pillar",
"SAF": "SAF",
"SAHARA": "Sahara",
"SATINFO": "Satellite Info",
"SATZLESEN": "Record Read",
"SAUGSTRAHLPUMPE": "Suction Jet Pump",
"SAVING": "Saving",
"SBC": "Sensotronic Brake Control",
"SCAN": "Scan",
"SCHAERFEN": "Arm",
"SCHALTEN": "Switch",
"SCHALTER": "Switch",
"SCHALTERBLOCK": "Switch Block",
"SCHALTERSPANNUNG": "Switch Voltage",
"SCHALTERSTATI": "Switch States",
"SCHALTUNG": "Shifting",
"SCHALTVENTILE": "Shift Valves",
"SCHEIBE": "Window",
"SCHEINWERFER": "Headlight",
"SCHEINWERFERHERSTELLERDATEN": "Headlight Manufacturer Data",
"SCHICHTUNG": "Stratification",
"SCHIEBERWEG": "Slider Travel",
"SCHL": "Key",
"SCHLIESSEN": "Close",
"SCHLIESSZEIT": "Dwell Time",
"SCHLOSSNUESSE": "Lock Barrels",
"SCHLUESSEL": "Key",
"SCHLUESSELCODE": "Key Code",
"SCHLUESSELDATEN": "Key Data",
"SCHNELLTEST": "Quick Test",
"SCHNITTSTELLE": "Interface",
"SCHRITTANZAHL": "Step Count",
"SCHRITTMOTORE": "Stepper Motors",
"SCHRITTVERLUSTE": "Step Losses",
"SCHRITTZAHLEN": "Step Counts",
"SCHWELLE": "Threshold",
"SDARS": "Satellite Radio",
"SDIAG": "Service Diagnosis",
"SEARCH": "Search",
"SEC": "Second",
"SECONDARY": "Secondary",
"SECURITY": "Security",
"SEED": "Seed",
"SEEK": "Seek",
"SEITENSCHEIBENHEIZUNG": "Side Window Heating",
"SEKUNDAER": "Secondary",
"SEKUNDAERSPEICHER": "Secondary Memory",
"SELBST": "Self",
"SELBSTHALTUNG": "Self-Latching",
"SELBSTTEST": "Self Test",
"SELECT": "Select",
"SELECTION": "Selection",
"SELECTIV": "Selective",
"SELEKTIV": "Selective",
"SELF": "Self",
"SELFTEST": "Self-Test",
"SEMISCHLUPF": "Semi Slip",
"SEND": "Send",
"SENDE": "Send",
"SENDELEIST": "Transmit Power",
"SENSE": "Sense",
"SENSOR": "Sensor",
"SENSORCLUSTER": "Sensor Cluster",
"SENSOREN": "Sensors",
"SENSORPARAMETER": "Sensor Parameters",
"SEQUENCE": "Sequence",
"SER": "Serial",
"SERIAL": "Serial",
"SERIENNR": "Serial Number",
"SERNR": "Serial Number",
"SERVER": "Server",
"SERVICE": "Service",
"SERVICEZAEHLER": "Service Counter",
"SERVO": "Servo",
"SERVOTRONIC": "Servotronic",
"SERVOTRONIK": "Servotronic",
"SERVZEIT": "Service Time",
"SESSION": "Session",
"SET": "Set",
"SETZE": "Set",
"SG": "Control Unit",
"SGTEMP": "Control Unit Temp",
"SHACKHARTMANN": "Shack-Hartmann",
"SHADOW": "Shadow",
"SHD": "Sunroof",
"SHDN": "Shutdown",
"SHIFT": "Shift",
"SHIFTING": "Shifting",
"SHIFTLEV": "Shift Lever",
"SHUTDOWN": "Shutdown",
"SHUTTER": "Shutter",
"SHZH": "Auxiliary Heating",
"SIA": "Service Interval",
"SICHERHEIT": "Safety",
"SICHERHEITSFAHRZEUG": "Security Vehicle",
"SIEMENS": "Siemens",
"SIGNAL": "Signal",
"SIGNALAUSGABE": "Signal Output",
"SIGNALE": "Signals",
"SIGNALS": "Signals",
"SIGNATURPRUEFUNG": "Signature Check",
"SIGNATURTEST": "Signature Test",
"SIMULATION": "Simulation",
"SIMULTAN": "Simultaneous",
"SINK": "Sink",
"SINUSGENERATOR": "Sine Generator",
"SIRENE": "Siren",
"SITZTIEFE": "Seat Depth",
"SKALIERUNG": "Scaling",
"SLAVE": "Slave",
"SLEEP": "Sleep",
"SLEEPTIMEOUT": "Sleep Timeout",
"SLIDE": "Slide",
"SLP": "Secondary Air Pump",
"SLS": "Tank Leak Diagnosis",
"SLV": "Secondary Air Valve",
"SMC": "SMC",
"SMG": "Sequential Manual Gearbox",
"SN": "Serial Number",
"SNR": "Serial Number",
"SOFORT": "Immediate",
"SOFT": "Soft",
"SOFTWARELOADING": "Software Loading",
"SOFTWARENAME": "Software Name",
"SOLL": "Target",
"SOLLAGE": "Target Position",
"SOLLDREHZAHL": "Target RPM",
"SOLLKONFIGURATION": "Target Configuration",
"SOLLSTAND": "Target Level",
"SOLLSTROM": "Target Current",
"SOLLWERT": "Target Value",
"SOLLWERTE": "Target Values",
"SONDE": "Sensor",
"SONDENDIAG": "Oxygen Sensor Diagnosis",
"SONDENHEIZUNG": "Sensor Heating",
"SONDERJOB": "Special Job",
"SONNENROLLO": "Sun Blind",
"SOS": "SOS",
"SOUND": "Sound",
"SOURCE": "Source",
"SOURCES": "Sources",
"SPAET": "Late",
"SPANNKRAFT": "Clamping Force",
"SPANNUNGEN": "Voltages",
"SPANNUNGSWERTE": "Voltage Values",
"SPEECH": "Speech",
"SPEED": "Speed",
"SPEICHERN": "Save",
"SPERRBEDINGUNGEN": "Lock Conditions",
"SPERRE": "Lock",
"SPERRSTELLUNG": "Lock Position",
"SPEZDATEN": "Special Data",
"SPEZIAL": "Special",
"SPEZIALMODI": "Special Modes",
"SPEZIFISCHE": "Specific",
"SPIEGEL": "Mirror",
"SPIEGELHEIZUNG": "Mirror Heating",
"SPORTMODUS": "Sport Mode",
"SPRACHEN": "Languages",
"SPRACHPAKET": "Language Pack",
"SPRACHVARIANTE": "Language Variant",
"SPRITZBEGINN": "Injection Start",
"SPRITZDUESEN": "Spray Nozzles",
"SPUELEN": "Purge",
"SR": "Sunroof",
"SRA": "Headlight Washer",
"SSECUHVN": "SSECUHVN",
"SSI": "SSI",
"SSP": "SSP",
"STA": "Starter",
"STABILITY": "Stability",
"STACK": "Stack",
"STACKCHECK": "Stack Check",
"STAENDE": "Levels",
"STAND": "Level",
"STANDALONE": "Standalone",
"STANDARDABSICHERUNG": "Standard Protection",
"STANDARDISIERUNG": "Standardization",
"STANDHEIZEN": "Auxiliary Heating",
"STAR": "Star",
"STARTEN": "Start",
"STARTWERT": "Start Value",
"STARTWERTE": "Start Values",
"STARTWERTPROGRAMMIERUNG": "Start Value Programming",
"STARTWERTRUECKSETZUNG": "Start Value Reset",
"STARTZAEHLER": "Start Counter",
"STAT": "Status",
"STATE": "State",
"STATI": "Status",
"STATION": "Station",
"STATISTIC": "Statistic",
"STATISTIK": "Statistics",
"STATISTIKDATEN": "Statistics Data",
"STATISTIKDATENSATZ": "Statistics Record",
"STATISTIKZAEHLER": "Statistics Counter",
"STATUSBYTE1": "Status Byte 1",
"STATUSBYTE2": "Status Byte 2",
"STATUSBYTE3": "Status Byte 3",
"STATUSBYTE4": "Status Byte 4",
"STATUSBYTE5": "Status Byte 5",
"STATUSINFORMATIONEN": "Status Information",
"STEGDREHZAHL": "Web Speed",
"STELLEN": "Set",
"STELLER": "Actuator",
"STELLUNG": "Position",
"STEPPER": "Stepper",
"STEPS": "Steps",
"STEPTRONIC": "Steptronic",
"STEUERGERAET": "Control Unit",
"STEUERGERAETE": "Control Units",
"STEUERGERAETESTATUS": "Control Unit Status",
"STEUERORT": "Control Location",
"STOERANZEIGE": "Fault Display",
"STOP": "Stop",
"STOPPEN": "Stop",
"STRECKE": "Distance",
"STROEME": "Currents",
"STROM": "Current",
"STROMABGLEICH": "Current Calibration",
"STROMREGLER": "Current Regulator",
"STROMWERTE": "Current Values",
"STUETZPUNKTGITTER": "Support Point Grid",
"STUFE": "Stage",
"SUBBUS": "Sub-Bus",
"SUCHBELEUCHTUNG": "Search Lighting",
"SUCHLAUF": "Scan",
"SUMME": "Sum",
"SUMMENLENKWINKEL": "Total Steering Angle",
"SUMMER": "Buzzer",
"SUPPLIER": "Supplier",
"SUPPLY": "Supply",
"SUPPORT": "Support",
"SVK": "System Components Identification",
"SVS": "Service",
"SVT": "Vanos Adjustment",
"SW": "Software",
"SWITCH": "Switch",
"SWNR": "Software Number",
"SYMBOLBELEUCHTUNG": "Symbol Lighting",
"SYMBOLISCH": "Symbolic",
"SYNC": "Sync",
"SYSTEM": "System",
"SYSTEMAUDIO": "System Audio",
"SYSTEMKONTEXTE": "System Contexts",
"SYSTEMSTATUS": "System Status",
"SYSTEMTEST": "System Test",
"SYSTEMZEIT": "System Time",
"SYSTEMZEITEN": "System Times",
"SYSTEMZUSTAND": "System State",
"SZL": "Steering Column Switch",
"SZM": "Center Switch Module",
"TAB": "Table",
"TABELLE": "Table",
"TABLE": "Table",
"TACHO": "Speedometer",
"TACHOPULSE": "Speedometer Pulse",
"TAGE": "Days",
"TAN": "TAN",
"TANK": "Tank",
"TANKINHALT": "Tank Content",
"TANKLECK": "Tank Leak",
"TAST": "Button",
"TASTE": "Button",
"TASTEN": "Buttons",
"TASTENBELEUCHTUNG": "Button Illumination",
"TASTENSTATUS": "Button Status",
"TASTER": "Button",
"TASTVERHAELTNIS": "Duty Cycle",
"TCU": "Transmission Control Unit",
"TEACHEN": "Teach",
"TEILE": "Parts",
"TEILENUMMER": "Part Number",
"TEILNEHMER": "Participant",
"TEL": "Telephone",
"TELEFONNUMMER": "Phone Number",
"TELEFONNUMMERN": "Phone Numbers",
"TELEGRAMM": "Telegram",
"TEMPERATURABSCHALTWERTE": "Temperature Cutoff Values",
"TEMPERATURE": "Temperature",
"TEMPERATUREN": "Temperatures",
"TEMPERATURKOLLEKTIV": "Temperature Collective",
"TEMPERATURMONITOR": "Temperature Monitor",
"TEMPERATURSENSOR": "Temperature Sensor",
"TEMPERATURVERTEILUNG": "Temperature Distribution",
"TEMPOMAT": "Cruise Control",
"TESTABBRUCH": "Test Abort",
"TESTBILD": "Test Image",
"TESTBIT": "Test Bit",
"TESTBITMAP": "Test Bitmap",
"TESTEN": "Test",
"TESTER": "Tester",
"TESTJOB": "Test Job",
"TESTLAUF": "Test Run",
"TESTMAP": "Test Map",
"TESTMODUS": "Test Mode",
"TESTPLATZ": "Test Bench",
"TESTPRG": "Test Program",
"TESTSTAND": "Test Bench",
"TESTSTIM": "Test Stimulus",
"TESTTON": "Test Tone",
"TEVES": "Teves",
"TEVSYS": "Purge Valve System",
"THERMO": "Thermo",
"THERMOSTAT": "Thermostat",
"THR": "Throttle",
"THROTTLE": "Throttle",
"TILT": "Tilt",
"TIME": "Time",
"TIMEOUT": "Timeout",
"TIMEOUTDIAGNOSE": "Timeout Diagnosis",
"TIMER": "Timer",
"TIMING": "Timing",
"TIPP": "Tip",
"TJA": "Traffic Jam Assist",
"TKA": "TKA",
"TMC": "Traffic Message Channel",
"TMO": "Timeout",
"TO": "To",
"TOGGELN": "Toggle",
"TONE": "Tone",
"TORQUE": "Torque",
"TOTALMILAGE": "Total Mileage",
"TP": "Transport Protocol",
"TRACENUMMER": "Trace Number",
"TRACK": "Track",
"TRACKING": "Tracking",
"TRANSDIAG": "Transmission Diagnosis",
"TRANSFER": "Transfer",
"TRANSMITTER": "Transmitter",
"TRANSP": "Transport",
"TRANSPARENTMODE": "Transparent Mode",
"TRANSPONDER": "Transponder",
"TRANSPONDERKENNUNG": "Transponder ID",
"TRANSPORTMODE": "Transport Mode",
"TRANSPORTSICHERUNG": "Transport Lock",
"TREBLE": "Treble",
"TRIGGER": "Trigger",
"TRIM": "Trim",
"TRIMMREG": "Trim Reg",
"TRIP": "Trip",
"TRSP": "Transponder",
"TUER": "Door",
"TUEREN": "Doors",
"TUNE": "Tune",
"TUNER": "Tuner",
"TUNING": "Tuning",
"TURBINENDREHZAHL": "Turbine Speed",
"TURN": "Turn",
"TV": "Duty Cycle",
"TVSETCHANNEL": "TV Set Channel",
"TX": "TX",
"TYP": "Type",
"TYPE": "Type",
"UBAT": "Battery Voltage",
"UBATT": "Battery Voltage",
"UEBER": "Over",
"UEBERDREH": "Overrev",
"UEBERNEHMEN": "Apply",
"UEBERWACHUNG": "Monitoring",
"UEBERWACHUNGSBEREICHE": "Monitoring Ranges",
"UHR": "Clock",
"UHRZEIT": "Time",
"ULF": "Hands-Free Module",
"UMA": "Ambient",
"UMGEBUNGSDRUCK": "Ambient Pressure",
"UMGEBUNGSHELLIGKEIT": "Ambient Brightness",
"UMGEBUNGSTEMPERATUR": "Ambient Temp",
"UMLUFT": "Recirculated Air",
"UMSCHALTVENTIL": "Switchover Valve",
"UMSTELLUNG": "Changeover",
"UMWAELZPUMPE": "Circulation Pump",
"UNLOCK": "Unlock",
"UNTER": "Under",
"UP": "Subroutine",
"UPDATE": "Update",
"UPROG": "Subprogram",
"US": "Ultrasonic",
"USAGE": "Usage",
"USB": "USB",
"USER": "User",
"VA": "Front Axle",
"VAKUUM": "Vacuum",
"VALUES": "Values",
"VALVE": "Valve",
"VANOS": "VANOS",
"VANOSSPUELEN": "VANOS Flush",
"VAR": "Variant",
"VARIABLE": "Variable",
"VARIABLES": "Variables",
"VARIANT": "Variant",
"VARIANTEN": "Variants",
"VARIANTENINDEX": "Variant Index",
"VBAT": "Battery Voltage",
"VCM": "Video Control Module",
"VDM": "Vertical Dynamics Management",
"VEHICLE": "Vehicle",
"VELOCITY": "Velocity",
"VENTIL": "Valve",
"VENTILE": "Valves",
"VENTILKENNLINIE": "Valve Curve",
"VER": "Version",
"VERBAU": "Installation",
"VERBAUT": "Installed",
"VERBRAUCH": "Consumption",
"VERBRAUCHERPRIORITAETEN": "Consumer Priorities",
"VERBRAUCHERREDUZIERUNG": "Load Reduction",
"VERBUNDEN": "Connected",
"VERDAMPF": "Evaporator",
"VERDECK": "Convertible Top",
"VERDECKLAUF": "Convertible Top Run",
"VERDECKZAEHLER": "Convertible Top Counter",
"VERRIEGELUNG": "Locking",
"VERSCHLEISSDATEN": "Wear Data",
"VERSIONEN": "Versions",
"VERSIONIERUNG": "Versioning",
"VERSIONINFO": "Version Info",
"VERSIONS": "Versions",
"VERSIONSNUMMERN": "Version Numbers",
"VERSORGUNG": "Supply",
"VERSORGUNGEN": "Supplies",
"VERSORGUNGSSPANNUNG": "Supply Voltage",
"VERSORGUNGSSPANNUNGEN": "Supply Voltages",
"VERST": "Amplifier",
"VERSTAERKUNG": "Gain",
"VERSTELL": "Adjustment",
"VERSTELLBEREICH": "Adjustment Range",
"VERSTELLEN": "Adjust",
"VERSTELLWINKEL": "Adjustment Angle",
"VERSTELLZEIT": "Adjustment Time",
"VERTAUSCHT": "Swapped",
"VERTEILUNG": "Distribution",
"VERTICAL": "Vertical",
"VERWERFEN": "Discard",
"VG": "Transfer Case",
"VIA": "Via",
"VIDEOEINGANG": "Video Input",
"VIDEOVERBINDUNG": "Video Connection",
"VIMDISA": "Intake DISA",
"VIN": "VIN",
"VIRTUELL": "Virtual",
"VKAT": "Pre-Catalyst",
"VMAX": "Max Speed",
"VOICE": "Voice",
"VOL": "Volume",
"VOLLSCHRITT": "Full Step",
"VOLT": "Volt",
"VOLTAGE": "Voltage",
"VOLUME": "Volume",
"VOLUMEAUDIO": "Volume Audio",
"VON": "From",
"VORBEREITEN": "Prepare",
"VORFOERDERPUMPE": "Pre-Feed Pump",
"VORGEBEN": "Preset",
"VORGLUEHLAMPE": "Glow Plug Indicator",
"VORN": "Front",
"VSYNC": "VSync",
"VVT": "VVT",
"WACH": "Awake",
"WAEHLHEBEL": "Selector Lever",
"WAEHLHEBELSTELLUNG": "Selector Lever Position",
"WAKE": "Wake",
"WAKEUP": "Wakeup",
"WANDLER": "Converter",
"WANDLERSTROM": "Converter Current",
"WANDLERUEBERBR": "Converter Lockup",
"WARMLUFT": "Warm Air",
"WARNBLINKEN": "Hazard Flashing",
"WARNEREIGNIS1": "Warning Event 1",
"WARNEREIGNIS2": "Warning Event 2",
"WARNEREIGNIS3": "Warning Event 3",
"WARNLAMPE": "Warning Lamp",
"WARNUNGSZAEHLER": "Warning Counter",
"WARPING": "Warping",
"WARTEN": "Wait",
"WARTEZEIT": "Wait Time",
"WASCHDUESE": "Washer Nozzle",
"WASCHPUMPE": "Washer Pump",
"WASCHWASSER": "Washer Fluid",
"WASSERPUMPE": "Water Pump",
"WASSERVENTIL": "Water Valve",
"WASSERVENTILE": "Water Valves",
"WATCHDOG": "Watchdog",
"WAVEBAND": "Waveband",
"WD": "Watchdog",
"WECHSEL": "Change",
"WECHSELCODE": "Rolling Code",
"WECKRINGSPEICHER": "Wake Ring Buffer",
"WEGE": "Paths",
"WEISSABGLEICH": "White Balance",
"WEITER": "Continue",
"WERK": "Factory",
"WERKSEINSTELLUNG": "Factory Setting",
"WERKSPROZESS": "Factory Process",
"WERKST": "Workshop",
"WERKSTATT": "Workshop",
"WERT": "Value",
"WERTE": "Values",
"WHEEL": "Wheel",
"WIDERSTAND": "Resistance",
"WIEDERHOL": "Repeat",
"WIEDERHOLZAEHLER": "Repeat Counter",
"WINDABWEISER": "Wind Deflector",
"WINDLAUF": "Cowl",
"WINDSCHOTT": "Wind Deflector",
"WINKEL": "Angle",
"WINKELWERTE": "Angle Values",
"WIPER": "Wiper",
"WISCHERABLAGENHEIZUNG": "Wiper Park Heating",
"WISCHERMOTOR": "Wiper Motor",
"WISCHERTASTER": "Wiper Switch",
"WISH": "Wish",
"WLC": "Wireless Charging",
"WOCHEN": "Weeks",
"WRITE": "Write",
"WS": "Workshop",
"WUP": "Wake-Up",
"XDUMP": "X Dump",
"XENON": "Xenon",
"XXL": "XXL",
"YEAR": "Year",
"ZAEHLERSTAENDE": "Counter Readings",
"ZCS": "Vehicle Order",
"ZEICHN": "Sign",
"ZEIGER": "Pointer",
"ZEIGERZAHL": "Pointer Count",
"ZEITINSPEKTIONSZAEHLER": "Time Inspection Counter",
"ZEITSTRAHL": "Timeline",
"ZENTRALCODE": "Central Code",
"ZENTRALE": "Central",
"ZERO": "Zero",
"ZERTIFIKAT": "Certificate",
"ZF": "ZF",
"ZFLS": "Steering",
"ZIF": "ZIF",
"ZSI": "ZSI",
"ZUENDKREISE": "Ignition Circuits",
"ZUENDKREISWIDERSTAENDE": "Ignition Circuit Resistances",
"ZUENDWINKEL": "Ignition Angle",
"ZUHEIZER": "Auxiliary Heater",
"ZURUECK": "Back",
"ZURUECKNEHMEN": "Retract",
"ZURUECKSETZEN": "Reset",
"ZUSAMMENBAUNUMMER": "Assembly Number",
"ZUSATZ": "Additional",
"ZUSATZFUNKTIONEN": "Additional Functions",
"ZUSATZLUEFTER": "Auxiliary Fan",
"ZUSATZWASSERPUMPE": "Auxiliary Water Pump",
"ZUSTAENDE": "States",
"ZUSTAND": "State",
"ZUSTANDS": "State",
"ZV": "Central Locking",
"ZVFH": "Central Locking Remote",
"ZWANGSHOCHSCHALTUNG": "Forced Upshift",
"ZWDIAG": "Intermediate Diagnosis",
"ZWP": "Auxiliary Water Pump",
"ZYL": "Cylinder"
};
