#!/usr/bin/env python3
"""
SA option numbers -> English names, off the ETK parts catalogue.

    tools/etk_sa_names.py --db etk.sqlite        # -> data/sa-names.json
                                                 #    app/renderer/data/sanames.js

BMW reuses SA numbers: 199 was "without catalytic converter" until 1999-08 and
"Equipment for leaded fuel" after. So an SA number alone does not name an
option -- the number AND the build date do. Every validity window is kept and
the renderer picks the one the car's production date falls in
(VehicleIdentity.saName). Never collapse the windows to one name per number.

Source tables (w_bed_sala rows are the option/country/package/... codes,
w_bed carries each one's text code, w_ben_gk the text in every language):

    w_bed_sala.bedsala_pnr         the number as printed ("530")
    w_bed_sala.bedsala_art         S = option (SA), L = country version,
                                   Q = package, N = accessory, V = model
                                   variant, X/Y = other catalogue codes
    w_bed_sala.bedsala_produktart  P = cars, M = motorcycles
    w_bed_sala.bedsala_gilt_v/_b   valid from / until (YYYYMMDD; until may
                                   be empty = still current)

Only cars and the English base text (ben_iso='en', no region) are exported.

Output shape (data/sa-names.json):
    { "530": [["S", 19830101, 0, "Air conditioning"],
              ["X", 20040204, 0, "RDC"]], ... }
Each entry is [art, from, until, name]; until 0 = open-ended.
"""
import argparse
import json
import os
import sqlite3

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..')
OUT = os.path.join(ROOT, 'data', 'sa-names.json')
OUT_JS = os.path.join(ROOT, 'app', 'renderer', 'data', 'sanames.js')

SQL = """
SELECT s.bedsala_pnr, s.bedsala_art, s.bedsala_gilt_v, s.bedsala_gilt_b,
       g.ben_text
FROM w_bed_sala s
JOIN w_bed b   ON b.bed_elemid = s.bedsala_id
JOIN w_ben_gk g ON g.ben_textcode = b.bed_textcode
WHERE s.bedsala_produktart = 'P'
  AND g.ben_iso = 'en'
  AND (g.ben_regiso IS NULL OR trim(g.ben_regiso) = '')
"""


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n\n')[0])
    ap.add_argument('--db', required=True, help='etk.sqlite (the dumped catalogue)')
    args = ap.parse_args()

    con = sqlite3.connect(args.db)
    out = {}
    seen = set()
    for pnr, art, von, bis, text in con.execute(SQL):
        text = ' '.join(str(text or '').split())
        pnr = str(pnr or '').strip()
        if not text or not pnr.isdigit():
            continue
        key = str(int(pnr))               # "0530" and "530" are one number
        von = int(von or 0)
        bis = int(bis or 0)
        row = (art, von, bis, text)
        if (key, row) in seen:
            continue
        seen.add((key, row))
        out.setdefault(key, []).append(list(row))
    for rows in out.values():
        rows.sort(key=lambda r: (r[0] != 'S', r[1], r[0], r[3]))

    with open(OUT, 'w') as fh:
        json.dump(out, fh, separators=(',', ':'), sort_keys=True,
                  ensure_ascii=False)
    print(f'wrote {OUT} ({os.path.getsize(OUT)} bytes, {len(out)} numbers)')

    os.makedirs(os.path.dirname(OUT_JS), exist_ok=True)
    with open(OUT_JS, 'w') as fh:
        fh.write('// SA option numbers -> English names with validity windows, '
                 'off the ETK catalogue.\n')
        fh.write('// Generated by tools/etk_sa_names.py -- do not edit by hand.\n')
        fh.write('window.BMW_SA_NAMES=')
        json.dump(out, fh, separators=(',', ':'), sort_keys=True,
                  ensure_ascii=False)
        fh.write(';\n')
    print(f'wrote {OUT_JS} ({os.path.getsize(OUT_JS)} bytes)')


if __name__ == '__main__':
    main()
